# Generated by Django 5.1.14 on 2025-11-08 13:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025,
                            11,
                            8,
                            13,
                            39,
                            23,
                            488112,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogs.blog"
                    ),
                ),
            ],
        ),
    ]
