# Generated by Django 5.1.14 on 2025-11-11 09:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 11, 9, 18, 48, 825427, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025,
                            11,
                            11,
                            9,
                            18,
                            48,
                            825871,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "opening_graphic",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField()),
                ("lockedToSubscribers", models.BooleanField(default=False)),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogs.blog"
                    ),
                ),
            ],
        ),
    ]
