# Generated by Django 5.1.14 on 2025-11-11 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_subscription_created_at_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="publication_time",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 11, 9, 23, 45, 711992, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 11, 9, 23, 45, 711252, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
