# Generated by Django 5.1.14 on 2025-11-23 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_subscription_subscriber_alter_blogpost_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 23, 13, 19, 46, 295906, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 23, 13, 19, 46, 296454, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 23, 13, 19, 46, 296873, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 23, 13, 19, 46, 295429, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
