# Generated by Django 5.1.14 on 2025-12-06 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0008_alter_blogpost_created_at_alter_comment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="view",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
