# Generated by Django 5.1.14 on 2025-12-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0010_blog_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="lockedToSubscribers",
            new_name="locked_to_subscribers",
        ),
    ]
