# Generated by Django 5.1.14 on 2025-12-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0011_rename_lockedtosubscribers_blogpost_locked_to_subscribers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="opening_graphic",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
