# Generated by Django 5.1.14 on 2025-12-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0012_alter_blogpost_body_alter_blogpost_opening_graphic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="opening_graphic",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
