# Generated by Django 5.1.14 on 2025-12-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0013_alter_blogpost_opening_graphic"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="post_type",
            field=models.CharField(
                choices=[("PU", "Published"), ("SCH", "Scheduled"), ("DR", "Drafts")],
                default="DR",
                max_length=255,
            ),
        ),
    ]
