# Generated by Django 5.1.14 on 2025-12-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0014_blogpost_post_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
