# Generated by Django 5.1.14 on 2025-12-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0015_blogpost_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("PU", "Published"),
                    ("SCH", "Scheduled"),
                    ("DR", "Drafts"),
                    ("DE", "Deleted"),
                ],
                default="DR",
                max_length=255,
            ),
        ),
    ]
