# Generated by Django 5.1.14 on 2025-12-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0016_alter_blogpost_post_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="body",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
