# Generated by Django 5.1.14 on 2025-12-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0017_comment_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="is_deleted",
        ),
    ]
