# Generated by Django 5.1.14 on 2025-12-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0019_commentlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
