# Generated by Django 5.1.14 on 2026-01-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0020_comment_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
