# Generated by Django 5.1.14 on 2026-01-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0021_alter_subscription_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_active",
        ),
    ]
