# Generated by Django 5.1.14 on 2025-11-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_banner",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
